cms/config/sync/admin-role.strapi-super-admin.json, cms/config/sync/core-store.plugin_content_manager_configuration_content_types##api##protection-coverage-stat.protection-coverage-stat.json
=> Config sync

cms/package.json, cms/yarn.lock
=> Strapi upgrade 4.14.5

frontend/Dockerfile, frontend/Dockerfile.prod, frontend/src/types/generated/strapi.schemas.ts
I've noticed the client is crashing [when tries to build during the deploy](https://github.com/Vizzuality/skytruth-30x30/actions/runs/6574046815/job/17858284158) and I think it's related with the fact the dependencies were being installed with Yarn v1 (included in Node by default) and not the version set by the application (3.5.0): ensuring it installs the dependencies with the correct Yarn version seems to fix the issue.
–
---
=> [N/A]: fixes app building in Dockerfile

cms/src/api/fishing-protection-level-stat/content-types/fishing-protection-level-stat/schema.json, cms/src/api/habitat-stat/content-types/habitat-stat/schema.json, cms/src/api/mpa-protection-coverage-stat/content-types/mpa-protection-coverage-stat/schema.json, cms/src/api/mpa/content-types/mpa/schema.json, cms/src/api/mpaa-establishment-stage-stat/content-types/mpaa-establishment-stage-stat/schema.json, cms/src/api/mpaa-protection-level-stat/content-types/mpaa-protection-level-stat/schema.json, cms/src/api/protection-coverage-stat/content-types/protection-coverage-stat/schema.json
Follow up on #21, changed precision to 12,2 on all decimal columns
---
=> Increased precision again to fit the biggest values

cms/export_custom-db.json
Current db export from staging.
---
=> data export sync

frontend/src/components/charts/horizontal-bar-chart/index.tsx, frontend/src/constants/habitat-chart-colors.ts, frontend/src/types/generated/strapi.schemas.ts
**In this PR**: 
- Changes to the "Proportion of Habitat" widgets colors  
- Add a slight border to the 30% threshold line for contrast purposes
FE Task: [SKY30-115](https://vizzuality.atlassian.net/browse/SKY30-115)
Design Task: [SKY30-114](https://vizzuality.atlassian.net/browse/SKY30-114)
[SKY30-115]: https://vizzuality.atlassian.net/browse/SKY30-115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SKY30-114]: https://vizzuality.atlassian.net/browse/SKY30-114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Habitat widget bar chart tweaks  

cms/export_custom-db.json
=> Updated data export

cms/config/middlewares.ts
https://vizzuality.atlassian.net/browse/SKY30-83
---
=> SKY30-83 Increased the file size limit for purposes of imports

cms/config/api.ts
Increases hard pagination to 300.
---
=> increases hard pagination limit to 300

frontend/src/containers/data-tool/sidebar/widgets/establishment-stages/index.tsx
=> fixes location type

.github/workflows/deploy.yml, cloud_functions/analysis/connect_tcp.py, cloud_functions/analysis/main.py, cloud_functions/analysis/requirements.txt, infrastructure/README.md, infrastructure/base/.terraform.lock.hcl, infrastructure/base/modules/cloudfunction/main.tf, infrastructure/base/modules/cloudfunction/outputs.tf, infrastructure/base/modules/cloudfunction/variables.tf, infrastructure/base/modules/env/main.tf, infrastructure/base/modules/env/outputs.tf, infrastructure/base/modules/secret_value/main.tf, infrastructure/base/modules/secret_value/outputs.tf, infrastructure/base/outputs.tf, infrastructure/base/versions.tf
Sets up resources and deployment workflow for the analysis cloud function.
https://vizzuality.atlassian.net/jira/software/c/projects/SKY30/boards/99/backlog?assignee=5caf0609d29bc104be1a316c&issueParent=23169&selectedIssue=SKY30-141&atlOrigin=eyJpIjoiMTkyYTZlZTMzNDg1NDYxMDkyMzNlYWVlZjQ4MmJlYjUiLCJwIjoiaiJ9
---
=> Analysis cloud function

frontend/src/containers/data-tool/content/details/tables/global-regional/index.tsx, frontend/src/containers/data-tool/content/details/tables/global-regional/useColumns.tsx, frontend/src/containers/data-tool/content/details/tables/national-highseas/index.tsx, frontend/src/containers/data-tool/sidebar/widgets/marine-conservation/index.tsx
This PR updates the widgets / tables to be compatible with the new data format. 
[SKY30-153 | Update data format ](https://vizzuality.atlassian.net/browse/SKY30-153)
=> [SKY30-153] update data format

frontend/src/containers/homepage/intro/index.tsx
Only _"Current global ocean protected area"_, as we've decided the rest we don't have data for. 
[SKY30-156 | Link home page numbers to real data](https://vizzuality.atlassian.net/browse/SKY30-156)
=> [SKY30-156] Link home page numbers to real data

frontend/src/containers/data-tool/content/map/index.tsx, frontend/src/containers/data-tool/content/map/layers-toolbox/layers-list/index.tsx, frontend/src/containers/data-tool/content/map/popup/generic/index.tsx, frontend/src/containers/data-tool/content/map/popup/index.tsx, frontend/src/containers/data-tool/content/map/popup/protected-area/index.tsx, frontend/src/lib/json-converter/index.ts, frontend/src/lib/utils/formats.ts, frontend/src/styles/globals.css
https://vizzuality.atlassian.net/browse/SKY30-129
---
=> [SKY30-129]: tooltips for remaining layers

frontend/src/containers/data-tool/content/map/layers-toolbox/legend/establishment/index.tsx, frontend/src/lib/json-converter/index.ts, frontend/src/styles/icons/designated.svg, frontend/src/styles/icons/implemented.svg, frontend/src/styles/icons/managed.svg, frontend/src/styles/icons/proposed.svg
https://vizzuality.atlassian.net/browse/SKY30-158
---
=> [SKY30-158]: establishment legend

frontend/src/containers/homepage/intro/index.tsx, frontend/src/containers/homepage/intro/sidebar-item/index.tsx
This PR updates the homepage intro stats. 
N/A - Row 7  in the fixes spreadsheet.
=> Update homepage intro stats

frontend/src/containers/data-tool/content/map/popup/index.tsx, frontend/src/containers/data-tool/content/map/popup/regions/index.tsx, frontend/src/lib/json-converter/index.ts
The tooltip is identical to EEZ's one, with the difference we relay on different data coming from the layer to fetch stuff from the API.
Also, whenever a layer is added/removed, the tooltip will hide to avoid weird behaviours.
Last one: avoids source duplication to display/hide layer selector in tooltip. In some layers, with multiple styles, the source was counted many times regardless being the same.
---
=> [N/A]: Regions layer popup

frontend/src/containers/data-tool/content/map/index.tsx
Fixes issue when going to http://localhost:3000/data-tool/[location] won't initialise the map with the location's bounds.
N/A
---
=> [N/A]: fixes retrieving cached location data

frontend/src/components/static-pages/section/index.tsx, frontend/src/containers/about/logos-grid/index.tsx, frontend/src/layouts/static-page.tsx, frontend/src/pages/about/index.tsx
- Add lateral padding for the static pages section components on mobile  
- Quick minor tweaks for the About page vertical spacing between components based on existing ones
N/A
=> [N/A] Improve static pages' sections' paddings on mobile

frontend/src/containers/data-tool/content/details/table/filters-button/index.tsx, frontend/src/containers/data-tool/content/details/table/tooltip-button/index.tsx, frontend/src/containers/data-tool/content/details/tables/global-regional/useColumns.tsx, frontend/src/containers/data-tool/content/details/tables/national-highseas/useColumns.tsx
Changing filters in a `useEffect` is never a good idea 😬 . I've changed it so now the filters update is done in a more imperative way (when the new values is selected). Let me know if I haven't broken/removed anything else 😅 
N/A
---
=> [N/A]: fixes loop with filters in tables

frontend/src/containers/map/content/details/table/tooltip-button/index.tsx
This PR fixes the vertical alignment on the data tables' columns' tooltip buttons. 
N/A
=> [N/A] Improve tooltip button alignments on the data tables

infrastructure/base/main.tf, infrastructure/base/modules/env/main.tf, infrastructure/base/modules/env/outputs.tf, infrastructure/base/modules/env/variables.tf, infrastructure/base/modules/load-balancer/main.tf, infrastructure/base/modules/load-balancer/variables.tf, infrastructure/base/outputs.tf
Pass cloud function traffic through load balancer to avoid CORS issues
---
=> Cloud function traffic through load balancer

cloud_functions/analysis/main.py
https://cloud.google.com/functions/docs/samples/functions-http-cors#functions_http_cors-python
=> CORS headers for the cloud function

cloud_functions/analysis/main.py
=> Allow CORS for POST

frontend/src/containers/map/content/details/index.tsx, frontend/src/containers/map/content/details/tables/global-regional/index.tsx, frontend/src/containers/map/content/details/tables/national-highseas/index.tsx, frontend/src/containers/map/sidebar/analysis/widget/index.tsx, frontend/src/containers/map/sidebar/details/index.tsx, frontend/src/containers/map/sidebar/details/location-selector/index.tsx
https://vizzuality.atlassian.net/browse/SKY30-173
---
=> [SKY30-173]: fixes getting location name

cms/database/migrations/2023.12.15T11.00.00.create_postgis_extension.js
=> Adds postgis to data schema

cloud_functions/analysis/src/analysis.py, cms/database/migrations/2023.12.19T10.00.00.move_postgis_extension_to_public.js
https://vizzuality.atlassian.net/browse/SKY30-176
=> [SKY30-176] Moved postgis to public schema and removed data. namespacing

cloud_functions/analysis/src/analysis.py
=> Fix: table namespace

infrastructure/base/main.tf, infrastructure/base/modules/cloudfunction/main.tf, infrastructure/base/modules/cloudfunction/variables.tf, infrastructure/base/modules/env/main.tf, infrastructure/base/modules/env/variables.tf, infrastructure/base/modules/sql/main.tf
Increased analysis cloud function timeout (180x), available memory (512) and max instances (2)
---
=> Increased analysis cloud function timeout, available memory and max instances

frontend/src/pages/about/index.tsx, frontend/src/pages/index.tsx, frontend/src/pages/privacy-policy.tsx, frontend/src/pages/terms-of-use.tsx
This PR fixes multiple CTAs and  buttons not being aligned to the same topic / not pointing to the correct page. 
CTAs were updated in the following pages: 
- Homepage  
- About  
- Privacy Policy  
- Terms of Use
[SKY30-179](https://vizzuality.atlassian.net/browse/SKY30-179)
[SKY30-179]: https://vizzuality.atlassian.net/browse/SKY30-179?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SKY30-179] Fix CTAs not pointing to the correct page

frontend/src/containers/map/sidebar/details/location-selector/index.tsx
Now the map popup is closed when a location is selected in the location selector.
https://vizzuality.atlassian.net/browse/SKY30-192
---
=> [SKY30-192] closes map popup on location change

cms/config/sync/admin-role.strapi-author.json, cms/config/sync/admin-role.strapi-editor.json
=> Editor and author permissions applied to all resources

frontend/src/pages/knowledge-hub/index.tsx
Makes knowledge hub title dynamic according to filter selection.
https://vizzuality.atlassian.net/browse/SKY30-202
---
=> [SKY30-202] makes knowledge hub title dynamic according to selection

frontend/src/containers/knowledge-hub/card-list/card-item/index.tsx, frontend/src/containers/knowledge-hub/card-list/index.tsx, frontend/src/types/generated/strapi.schemas.ts
Displays multiple resource types in cards.
https://vizzuality.atlassian.net/browse/SKY30-205
---
=> [SKY30-205] knowledge hub: displays multiple resource types

frontend/src/containers/map/sidebar/details/index.tsx, frontend/src/containers/map/sidebar/details/widgets/index.tsx
Sticks location selector and adds scrolling to the sidebar's content.
https://vizzuality.atlassian.net/browse/SKY30-199
---
=> [SKY30-199] sticks location selector and adds scroll to sidebar

frontend/src/components/charts/conservation-chart/index.tsx, frontend/src/containers/map/content/details/tables/global-regional/index.tsx, frontend/src/containers/map/content/details/tables/global-regional/useColumns.tsx, frontend/src/containers/map/content/details/tables/global-regional/useTooltips.tsx, frontend/src/containers/map/content/details/tables/national-highseas/useColumns.tsx, frontend/src/containers/map/content/details/tables/national-highseas/useTooltips.tsx, frontend/src/containers/map/sidebar/analysis/useTooltips.ts, frontend/src/containers/map/sidebar/details/widgets/habitat/index.tsx, frontend/src/containers/map/sidebar/details/widgets/protection-types/index.tsx, frontend/src/types/generated/strapi.schemas.ts
https://vizzuality.atlassian.net/browse/SKY30-200
---
=> [SKY30-200] tables: client feedback

README.md, cloud_functions/analysis/README.md, cms/README.md, frontend/README.md, hubspot.md, infrastructure/README.md, infrastructure/base/variables.tf, infrastructure/base/vars/terraform.tfvars
=> Documentation

frontend/src/containers/homepage/intro/index.tsx, frontend/src/containers/homepage/intro/sidebar-item/index.tsx
This had been merged as part of https://github.com/Vizzuality/skytruth-30x30/pull/137, but it looks like somehow the changes got lost during the other PR's merging and/or rebasing. 
[SKY30-177](https://vizzuality.atlassian.net/browse/SKY30-177)
[SKY30-177]: https://vizzuality.atlassian.net/browse/SKY30-177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SKY30-177] Homepage intro indicators to display one decimal place

frontend/src/pages/about/index.tsx
Add missing space to protected seas link in the partners section
N/A
=> Add missing space to protected seas link in the partners section

frontend/src/pages/about/index.tsx
This PR links the underlined text in the Definition section of the About page to the source website. 
[SKY30-224](https://vizzuality.atlassian.net/browse/SKY30-224)
[SKY30-224]: https://vizzuality.atlassian.net/browse/SKY30-224?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SKY30-224] Add new link to the Definition section of the about page

frontend/src/containers/map/content/details/tables/national-highseas/useTooltips.tsx
Use new tooltip slug for countries/highseas tables. 
[SKY30-208](https://vizzuality.atlassian.net/browse/SKY30-208)
[SKY30-208]: https://vizzuality.atlassian.net/browse/SKY30-208?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SKY30-208] Change area tooltips slug for countries/highseas tables to a new one

frontend/src/pages/index.tsx
Minor copy update to the context section of the homepage. 
[SKY30-240](https://vizzuality.atlassian.net/browse/SKY30-240)
=> [SKY30-240] Add missing proposition to the copy in the homepage context section

frontend/src/components/header.tsx
This PR changes the header navigation arrow color from black to violet. 
[SKY30-239](https://vizzuality.atlassian.net/browse/SKY30-239)
[SKY30-239]: https://vizzuality.atlassian.net/browse/SKY30-239?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SKY30-239] Update navigation arrow color for the about link

frontend/src/containers/map/content/map/popup/eez/index.tsx, frontend/src/containers/map/content/map/popup/generic/index.tsx, frontend/src/containers/map/content/map/popup/regions/index.tsx
This PR changes the formatting in the map popups from uppercase to mixed case. 
Some tweaks were done to the spacing as well in order to better approximate it to the designs. 
[SKY30-236](https://vizzuality.atlassian.net/browse/SKY30-236)
[SKY30-236]: https://vizzuality.atlassian.net/browse/SKY30-236?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SKY30-236] Map pop up box label formatting (uppercase to mixed case)

frontend/package.json, frontend/src/components/ui/command.tsx, frontend/src/containers/map/sidebar/details/index.tsx, frontend/src/containers/map/sidebar/details/location-selector/index.tsx, frontend/src/containers/map/sidebar/details/location-selector/location-dropdown/index.tsx, frontend/src/containers/map/sidebar/details/location-selector/type-toggle/index.tsx, frontend/tailwind.config.js, frontend/yarn.lock
- Added Location Type Toggle component for use in the Location Selector  
- Used LocationTypeToggle to filter locations in the LocationSelector  
- Moved LocationDropdown into its own component   
[SKY30-234](https://vizzuality.atlassian.net/browse/SKY30-234)
[SKY30-234]: https://vizzuality.atlassian.net/browse/SKY30-234?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SKY30-234] Add toggle to Location selector to choose between regions & countries/highseas

frontend/src/containers/map/content/details/tables/global-regional/index.tsx, frontend/src/containers/map/content/details/tables/global-regional/useColumns.tsx, frontend/src/containers/map/content/details/tables/national-highseas/index.tsx, frontend/src/containers/map/content/details/tables/national-highseas/useColumns.tsx, frontend/src/containers/map/content/details/tables/national-highseas/useFiltersOptions.ts
This PR implements small changes to the tables:  
- Rename tables columns' names  
- Remove the location type column from the global details table
[SKY30-243](https://vizzuality.atlassian.net/browse/SKY30-243)
[SKY30-243]: https://vizzuality.atlassian.net/browse/SKY30-243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SKY30-243] Implement design changes in the dashboard tables

frontend/src/containers/map/sidebar/index.tsx, frontend/src/containers/map/sidebar/modelling/index.tsx, frontend/src/containers/map/sidebar/modelling/modelling-intro/index.tsx
Update text/labels for anything related to conservation modelling
[SKY30-273](https://vizzuality.atlassian.net/browse/SKY30-273)
[SKY30-273]: https://vizzuality.atlassian.net/browse/SKY30-273?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SKY30-273] Update text/labels for anything related to conservation modelling

frontend/src/components/filters-button/index.tsx, frontend/src/containers/map/content/details/helpers.ts, frontend/src/containers/map/content/details/tables/global-regional/useColumns.tsx, frontend/src/containers/map/content/details/tables/global-regional/useFiltersOptions.ts, frontend/src/containers/map/content/details/tables/national-highseas/index.tsx
=> Change how table filtering works + fix filters' select all and clear all buttons

frontend/src/containers/map/content/map/layers-toolbox/index.tsx
Add scrolling to the Layers/Legend in the map when content doesn't fit
[SKY30-290](https://vizzuality.atlassian.net/browse/SKY30-290)
[SKY30-290]: https://vizzuality.atlassian.net/browse/SKY30-290?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SKY30-290] Add scrolling to the Layers/Legend in the map when content doesn't fit

frontend/src/containers/map/content/map/index.tsx
TODO
[SKY30-248](https://vizzuality.atlassian.net/browse/SKY30-248)
[SKY30-248]: https://vizzuality.atlassian.net/browse/SKY30-248?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SKY30-248] Select (keep selected) EEZ / Regions when the user clicks to open the popup

infrastructure/base/modules/env/main.tf
To improve analysis function performance
=> Upscaled db instance to 2 CPU

frontend/src/pages/index.tsx
This PR makes it so that the ocean protected area percentage, in the impacts section, is from the API calculations and not a hardcoded indicator. 
[SKY30-287](https://vizzuality.atlassian.net/browse/SKY30-287)
[SKY30-287]: https://vizzuality.atlassian.net/browse/SKY30-287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SKY30-287] Homepage ocean protected area percentage to be fetched from the API calculations

frontend/src/components/analytics/index.tsx, frontend/src/pages/_app.tsx
- New `Analytics` component  
- Setup for GTM based on the new Analytisc component
[SKY30-297](https://vizzuality.atlassian.net/browse/SKY30-297)
[SKY30-297]: https://vizzuality.atlassian.net/browse/SKY30-297?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SKY30-297] Add GTM scripts to the FE

frontend/package.json, frontend/src/middleware.ts, frontend/src/pages/api/auth/[...nextauth].ts, frontend/yarn.lock
This PR adds basic password protection support. 
[SKY30-316](SKY30-316-password-protection-for-production-site)
[SKY30-316]: https://vizzuality.atlassian.net/browse/SKY30-316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SKY30-316] Add support for basic Auth

cloud_functions/analysis/README.md, cloud_functions/analysis/src/analysis.py
=> Fix/cloud function/sky30 328 empty response db

frontend/src/containers/homepage/link-cards/index.tsx, frontend/src/containers/homepage/link-cards/link-card/index.tsx, frontend/src/pages/index.tsx
- Add a new _Conservation Builder_ card to the homepage  
- Change color and title for the _Progress Tracker_ card in the homepage  
- Section reordering: _Impact_ section now appears before the _Context one_  
- Cards now use the new urls (_Progress Tracker_ & _Conservation Builder_)  
**TODO:** 
- Update cards copy when provided  
- Verify that the sections are indeed to be reordered 
[SKY30-314](https://vizzuality.atlassian.net/browse/SKY30-314)
[SKY30-314]: https://vizzuality.atlassian.net/browse/SKY30-314?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SKY30-314] Implement revised designs for the homepage

frontend/src/containers/map/content/details/index.tsx
Add Icon next to the close button for the map details 
[SKY30-323](https://vizzuality.atlassian.net/browse/SKY30-323)
[SKY30-323]: https://vizzuality.atlassian.net/browse/SKY30-323?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Details pane close button to have an icon + layout changes

frontend/src/containers/map/content/map/draw-controls/index.tsx
Removes fitting bounds when the user draws a polygon on the map.
https://vizzuality.atlassian.net/browse/SKY30-329
---
=> [SKY30-329] removes map fit bounds after drawing polygon

frontend/src/components/map/draw-controls/hooks.ts
https://vizzuality.atlassian.net/browse/SKY30-330
---
=> [SKY30-330] updates styles of polygon

frontend/src/containers/map/sidebar/main-panel/details/widgets/habitat/index.tsx, frontend/src/containers/map/sidebar/main-panel/details/widgets/marine-conservation/index.tsx, frontend/src/containers/map/sidebar/main-panel/details/widgets/protection-types/index.tsx
Fixes crash navigation from `/` to `/progress-tracker` where the location data was not ready on time.
---
=> [N/A] waits for location data before requesting widget data

frontend/src/containers/homepage/link-cards/index.tsx
Some text updates in the homepage.
https://vizzuality.atlassian.net/browse/SKY30-340
---
=> [SKY30-340] updates homepage texts

cms/README.md, cms/config/sync/core-store.plugin_content_manager_configuration_content_types##api##mpa-protection-coverage-stat.mpa-protection-coverage-stat.json, cms/config/sync/core-store.plugin_content_manager_configuration_content_types##api##mpa.mpa.json, cms/src/api/mpa-protection-coverage-stat/content-types/mpa-protection-coverage-stat/schema.json, cms/src/api/mpa/content-types/mpa/schema.json, cms/src/api/mpaa-establishment-stage/content-types/mpaa-establishment-stage/schema.json, cms/types/generated/contentTypes.d.ts
=> [SKY30-317] Migrate column for stablishment stage from mpa table to mpa protection

frontend/src/containers/map/sidebar/main-panel/details/countries-list/index.tsx, frontend/src/containers/map/sidebar/main-panel/details/details-button/index.tsx
Follow up with a couple tweaks requested by design: 
- font weight for the details button on the sidebar  
- line height for the expandable list of countries
[SKY30-311](https://vizzuality.atlassian.net/browse/SKY30-311)
[SKY30-311]: https://vizzuality.atlassian.net/browse/SKY30-311?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SKY30-311] Implement design tweaks to the sidebar header

cloud_functions/analysis/src/analysis.py
=> bring back error catch when area is totally out of the marine realm

frontend/src/containers/map/content/map/index.tsx, frontend/src/containers/map/content/map/popup/eez/index.tsx, frontend/src/containers/map/content/map/popup/regions/index.tsx, frontend/src/containers/map/sidebar/main-panel/details/location-selector/index.tsx, frontend/src/containers/map/store.ts
Go to `/progress-tracker`, change the location. Go to another page of the site. Click on _Progress tracker_ link again. Map should display the global view, not the location.
https://vizzuality.atlassian.net/browse/SKY30-357
---
=> [SKY30-357] resets bounds location after unmounting map

frontend/src/containers/map/sidebar/main-panel/modelling/modelling-buttons/index.tsx
https://vizzuality.atlassian.net/browse/SKY30-356
---
=> [SKY30-356] keeps drawing when click on re-draw button

frontend/src/containers/map/content/details/tables/global-regional/useColumns.tsx, frontend/src/containers/map/content/details/tables/national-highseas/useColumns.tsx, frontend/src/containers/map/sidebar/main-panel/details/widgets/index.tsx
https://vizzuality.atlassian.net/browse/SKY30-355
---
=> [SKY30-355] hides temporary protected seas data

frontend/src/containers/map/content/map/index.tsx, frontend/src/containers/map/content/map/popup/index.tsx
https://vizzuality.atlassian.net/browse/SKY30-354
---
=> [SKY30-354]: hides hover tooltip when EEZ layer is not present

frontend/src/containers/map/content/details/tables/national-highseas/index.tsx
=> national table: updates area calc

frontend/src/containers/map/sidebar/main-panel/modelling/widget/index.tsx
https://vizzuality.atlassian.net/browse/SKY30-363
---
=> [SKY30-363] conservation builder: ensures only the most recent data is used

cms/config/sync/core-store.plugin_content_manager_configuration_content_types##api##mpa-protection-coverage-stat.mpa-protection-coverage-stat.json, frontend/src/containers/map/content/details/helpers.ts, frontend/src/containers/map/content/details/tables/national-highseas/index.tsx, frontend/src/types/generated/strapi.schemas.ts
https://vizzuality.atlassian.net/browse/SKY30-359
---
=> [SKY30-359] brings back map establishment stage column

frontend/src/containers/map/content/map/index.tsx
Fixes crash on mobile when the map tries to fit invalid bounds due to sidebar assumption.
---
=> [N/A] fixes map fit bounds on mobile

frontend/package.json
=> Attempt to fix deployment issues

frontend/Dockerfile.prod
=> Match docker config node js versions

cms/config/sync/user-role.public.json
=> Restore CMS public permissions

frontend/src/containers/map/sidebar/index.tsx, frontend/src/containers/map/sidebar/main-panel/panels/index.tsx, frontend/src/layouts/map.tsx, frontend/src/pages/conservation-builder/[locationCode].tsx
=> Fix incorrect type prop in the ConservationBuilderPage + typing

frontend/src/layouts/fullscreen.tsx, frontend/src/pages/contact.tsx
=> Fix ContactPage header not being translated

frontend/src/components/layer-preview/index.tsx, frontend/src/containers/map/content/details/tables/national-highseas/index.tsx, frontend/src/containers/map/content/details/tables/national-highseas/useColumns.tsx
https://vizzuality.atlassian.net/browse/SKY30-384
---
=> [SKY30-384] layer preview in national table

frontend/src/containers/map/content/details/tables/national-highseas/useTooltips.tsx
Add mapping for tooltips for the new _"Data Source"_ and _"IUCN Categories"_ columns in the national tables. 
Mapping:  
- Data Source: `details-data-source`  
- IUCN Category: `details-iucn-category`
[SKY30-429](https://vizzuality.atlassian.net/browse/SKY30-429)
[SKY30-429]: https://vizzuality.atlassian.net/browse/SKY30-429?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [SKY30-429] Add data-source and iucn-category mapping for national tables' new columns

data/notebooks/habitat2.ipynb, data/notebooks/pipes_mock/precalc.ipynb, data/notebooks/pipes_mock/tiles.ipynb
In notebook habitats2 I have modified some cells to move ATA values to ABNJ, along with small changes on the rest of the code.
In notebook precalc I've just modified the habitats table so that instead of habitats4 is habitats5.
In notebook tiles I have modified the protectedseas section.
=> changes in habitat statistics and protectedseas mbtiles creation

frontend/src/containers/map/content/details/tables/global-regional/index.tsx
This PR addresses an issue where the global table would be empty on staging when displayed in English or French, but complete when displayed in Spanish.
The root cause is how Strapi gives a different ID to different version of a same localised document.
The stats models are not localised and have a many-to-1 relation to the Location model, meaning they can only point to one version of a location instead of all them. For this reason, when the stats are loaded through the Location model, only one of the localised version has the link to the stats.
This PR mitigates the issue by loading all three localised version of a Location and determining which one has the relation to the stats model(s). This workaround had already been implemented for the Fishing Protection widget but not replicated …
=> Address issue where the data displayed in the global table would be different depending on locale

frontend/src/containers/map/sidebar/main-panel/panels/modelling/index.tsx, frontend/src/pages/conservation-builder/index.tsx
This PR removes the location search input and the location URL parameter from the Conservation Builder.
[SKY30-462](https://vizzuality.atlassian.net/browse/SKY30-462)
[SKY30-462]: https://vizzuality.atlassian.net/browse/SKY30-462?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove location-related code from the Conservation Builder

frontend/src/components/ui/skeleton.tsx, frontend/src/containers/map/content/details/tables/global-regional/hooks.tsx, frontend/src/containers/map/content/details/tables/global-regional/index.tsx, frontend/src/containers/map/content/details/tables/national-highseas/hooks.tsx, frontend/src/containers/map/content/details/tables/national-highseas/index.tsx, frontend/src/pages/_app.tsx
This PR adds skeletons to the tables to indicate to the user when they are loading.
[SKY30-487](https://vizzuality.atlassian.net/browse/SKY30-487)
[SKY30-487]: https://vizzuality.atlassian.net/browse/SKY30-487?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Indicate to the user when the tables are loading

cloud_functions/analysis/docker-compose.yml, cloud_functions/analysis/init.sh, cloud_functions/analysis/main.py, cloud_functions/analysis/src/analysis.py
=> added new functionality for terrestrial cloud function analysis

frontend/src/components/charts/conservation-chart/legend/index.tsx, frontend/src/components/map/zoom-controls/index.tsx, frontend/src/constants/fishing-protection-chart-colors.ts, frontend/src/containers/map/content/map/popup/boundaries/index.tsx, frontend/src/containers/map/content/map/popup/index.tsx, frontend/src/containers/map/sidebar/index.tsx, frontend/translations/en.json
This PR implements some feedback provided by the design team.
[SKY30-502](https://vizzuality.atlassian.net/browse/SKY30-502)
[SKY30-502]: https://vizzuality.atlassian.net/browse/SKY30-502?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Implement design feedback

README.md, cms/README.md, cms/config/sync/admin-role.strapi-super-admin.json, frontend/README.md, frontend/src/containers/map/sidebar/main-panel/panels/modelling/index.tsx, frontend/translations/en.json
This PR is to deploy https://github.com/SkyTruth/skytruth-30x30/pull/330 to prod
---------
---
=> Tech 2492: Deploy #330

frontend/package.json, frontend/src/components/analytics/index.tsx, frontend/src/pages/_app.tsx, frontend/src/pages/_document.tsx, frontend/yarn.lock
This PR updates how GTM is implemented, since it is currently not logging users to google analytics.
It appears to work locally in debug mode, but GA is set to accept streaming only from the prod site so there may be follow up PR's after testing in Prod
---
=> TECH-2705: Attempted fix for Google Tag Manager

frontend/src/containers/map/sidebar/main-panel/location-selector/index.tsx, frontend/src/containers/map/sidebar/main-panel/panels/details/index.tsx, frontend/src/containers/map/sidebar/main-panel/panels/details/widgets/marine-conservation/index.tsx, frontend/translations/en.json
=> Style fixes for the details sidebar

frontend/package.json, frontend/src/components/analytics/heap/index.tsx, frontend/src/containers/map/content/map/popup/boundaries/StatCard.tsx, frontend/src/containers/map/sidebar/main-panel/location-selector/index.tsx, frontend/src/containers/map/sidebar/main-panel/panels/details/countries-list/index.tsx, frontend/src/types/index.d.ts
=> TECH-3240: Add Heap tracking to custom regions
