SkyTruth/skytruth-30x30

frontend/src/components/charts/horizontal-bar-chart/index.tsx
frontend/src/components/widget/index.tsx
frontend/src/constants/habitat-chart-colors.ts
frontend/src/containers/data-tool/sidebar/widgets/habitat/index.tsx
frontend/src/containers/data-tool/sidebar/widgets/index.tsx

This PR implements the _"Proportion of Habitat within Protected and Conserved Areas"_ widget. 
It adds: 
- A new base `Widget` component
_in order to keep widget styles (mostly headers) consistent_   
- An `HorizontalBarChart` component   
_to be reused by the different widgets. See screenshot below_  
- Constants file mapping colors to use to slugs  
_perhaps this data should come from Strapi instead_  
- The Widget itself  
_fetching data from the API_  
**Notes:**  
- This PR is based on the Location selector one, as the location is needed in order to fetch the data  
- If the data for the widget is not available (eg: location with no data), the widget will not be displayed  
- **Important:**
- There are some layout issues that I'm trying to solve separately. 
- Although I've made the …

[SKY30-48] Proportion of habitat widget

---

frontend/src/components/ui/dialog.tsx
frontend/src/components/ui/sheet.tsx

Not sure why these warnings started popping up now.
The UI components don't seem to be in use now, so I've removed the `className` prop. 
This is preventing deployments for tomorrow so it's more of a quick fix.

Fix issue with ui/Dialog typing preventing deployments

---

cms/config/sync/core-store.plugin_content_manager_configuration_content_types##api##data-info.data-info.json
cms/config/sync/user-role.public.json

I forgot to export the permissions when committing the content type.
https://30x30.skytruth.org/cms/api/data-infos should not return 403
https://vizzuality.atlassian.net/browse/SKY30-81?atlOrigin=eyJpIjoiMTM5YTA0MTYxNDA0NDAzZmI1NjY4NTk3ZmViMDFmZTAiLCJwIjoiaiJ9
---

Permissions for public role to data info endpoints

---

frontend/src/containers/data-tool/sidebar/location-selector/index.tsx

This PR fixes a small bug with the location selector; it is currently searching by the location code instead of the actual text.  
The current change seemed to be the easier one to prevent extra work modifying the UI component. 
Verify that the Location Selector can search correctly. On staging it is searching by code (eg: `GLOB` triggers worldwide, while searching for `world` does not yield results. )
N/A

Location selector to search by name instead of code/slug

---

cms/config/sync/admin-role.strapi-super-admin.json
cms/config/sync/core-store.plugin_content_manager_configuration_content_types##api##location.location.json
cms/src/api/location/content-types/location/schema.json
cms/types/generated/contentTypes.d.ts

Adds `bounds` json field to store location bounds. It's an array of coordinates, e.g.
```
[
124.3727348,
32.9104556,
132.1467806,
38.623477
],
```
It is possible to set bounds for a location.
https://vizzuality.atlassian.net/browse/SKY30-84
---

Added location geographic bounding box as a JSON field

---

frontend/src/components/charts/horizontal-bar-chart/index.tsx

- Fix the "bar fill" percentage on the Habitat Widget  
_During sprint review I noticed that although the displayed percentages are calculated correctly (based on the totalArea, not the target of 30%), the bar fill was incorrect; it was filling in accordance to the target and not the total area. Eg: 84% total area protected, the bar would fill from 0% to 40% of the target of 30%._  
- Set the scale of the chart from 0% to 100% (instead of 0% to 55%)  
_this is based on the talk during the Sprint review conclusions; that we'll do 100% by now_
**Notes:**
- This widget (and respective chart, which will be used by other widgets) can already handle a variable max percentage to display (55% / 100%) and calculate the display accordingly;  
- The max percentage displayed is …

Fix habitat widget bar fill to be relative to total area + changing scale to 100%

---

cms/config/sync/core-store.plugin_content_manager_configuration_content_types##api##data-info.data-info.json
cms/config/sync/core-store.plugin_content_manager_configuration_content_types##api##fishing-protection-level-stat.fishing-protection-level-stat.json
cms/config/sync/core-store.plugin_content_manager_configuration_content_types##api##habitat-stat.habitat-stat.json
cms/config/sync/core-store.plugin_content_manager_configuration_content_types##api##location.location.json
cms/config/sync/core-store.plugin_content_manager_configuration_content_types##api##mpa-protection-coverage-stat.mpa-protection-coverage-stat.json
cms/config/sync/core-store.plugin_content_manager_configuration_content_types##api##mpa.mpa.json
cms/config/sync/core-store.plugin_content_manager_configuration_content_types##api##mpaa-establishment-stage-stat.mpaa-establishment-stage-stat.json
cms/config/sync/core-store.plugin_content_manager_configuration_content_types##api##protection-coverage-stat.protection-coverage-stat.json
cms/config/sync/user-role.public.json
frontend/package.json
frontend/src/components/header.tsx
frontend/src/containers/data-tool/content/index.tsx
frontend/src/containers/data-tool/content/map/index.tsx
frontend/src/containers/data-tool/content/map/layer-manager/item.tsx
frontend/src/containers/data-tool/content/map/sync-settings.ts
frontend/src/containers/data-tool/sidebar/index.tsx
frontend/src/containers/data-tool/sidebar/location-selector/index.tsx
frontend/src/containers/data-tool/sync-settings.ts
frontend/src/pages/data-tool/[locationCode].tsx
frontend/src/store/data-tool.ts
frontend/src/styles/globals.css
frontend/src/types/generated/strapi.schemas.ts
frontend/yarn.lock

This PR includes:
- EEZ layer styles for: hovering, selected and disputed/claimed zones. (Check the CMS)
- Changing location in the sidebar, will make the map to travel the specified bounds. (note there are some buggy bounds coming from the API, like USA and worlwide. But you can check others like Spain and Brazil and should work).
- Now the sidebar moves the map to the left when is hidden and viceversa. Also, I converted the local sidebar state into a global one as I needed in in the map.
https://www.figma.com/file/RQB86KnkGg4UTpqQZ09KBX/30x30-Design-%5BInternal%5D?node-id=610%3A17343&mode=dev
I've been working mainly with the staging CMS (https://30x30.skytruth.org/cms/admin), so if you test it locally, just make sure you are pointing to it. …

[SKY30-85]: bounds and highlight EEZ

---

frontend/src/containers/data-tool/content/map/index.tsx
frontend/src/containers/data-tool/content/map/labels-manager/index.tsx
frontend/src/containers/data-tool/content/map/layers-toolbox/layers-list/index.tsx
frontend/src/containers/data-tool/content/map/sync-settings.ts

This PR adds the ability to toggle on/off the labels in the map. It will also toggle labels listening to the URL.
https://vizzuality.atlassian.net/browse/SKY30-98
---

[SKY30-98]: toggles on/off labels in map

---

cms/config/sync/user-role.data_pipes_import_export_access.json
cms/config/sync/user-role.public.json

A new role (Data Pipes Import / Export Access) for authenticated users, with permissions for the import / export content API.
Additionally, restored permissions for Public role.
A user with this role will be able to run the import scripts.
https://vizzuality.atlassian.net/browse/SKY30-125
---

SKY30-125 Role for data pipes user

---

frontend/src/containers/data-tool/content/details/index.tsx
frontend/src/containers/data-tool/content/index.tsx
frontend/src/containers/data-tool/content/map/index.tsx
frontend/src/containers/data-tool/sidebar/details-button/index.tsx

This PR simple restores the DataTool's layout changes that affected the tables' display. 
Unfortunately it does not yet address why the map isn't adjusting to the container correctly (although the container's size and position is correct; can be tested by adding borders to it).
It also removes mentions the Sidebar definition from the DataTool's Map container; it is handled by a component above it, unlike in the initial map. 
N/A

Attempt to fix initial data-tool layout fixes

---

infrastructure/base/main.tf

Adds permissions for data bucket to the data pipelines service account. The existing account is imported into a resource terraform state, and the existing bucket referenced as a data source rather than resource. The permission is granted via `google_storage_bucket_iam_member`, so as not to upset the existing bucket policy.
---

Permissions for data pipelines service account

---

frontend/src/containers/data-tool/content/details/table/tooltip-button/index.tsx
frontend/src/containers/data-tool/content/details/tables/global-regional/index.tsx
frontend/src/containers/data-tool/content/details/tables/global-regional/useColumns.tsx
frontend/src/containers/data-tool/content/details/tables/global-regional/useTooltips.tsx
frontend/src/containers/data-tool/content/details/tables/national-highseas/index.tsx
frontend/src/containers/data-tool/content/details/tables/national-highseas/useColumns.tsx
frontend/src/containers/data-tool/content/details/tables/national-highseas/useTooltips.tsx

This PR adds tooltips to the data table's column headers
**Note:**  
Some things may need to be changed; perhaps on hover instead of click and/or extract the `useTooltips` hooks to a single one, because the widgets will also have tooltips added to them. 
[SKY30-92](https://vizzuality.atlassian.net/browse/SKY30-92)
[SKY30-92]: https://vizzuality.atlassian.net/browse/SKY30-92?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SKY30-92] Add tooltips to the data tables headers

---

frontend/src/components/charts/horizontal-bar-chart/index.tsx
frontend/src/constants/protection-types-chart-colors.ts
frontend/src/containers/data-tool/sidebar/widgets/index.tsx
frontend/src/containers/data-tool/sidebar/widgets/protection-types/index.tsx

- Add the _"Marine Conservation Protection Types"_ widget to the Data Tool  
- Adjust HorizontalBarChart Widgets units to match the updated designs
**Notes:**  
- Tooltips not yet implemented  
_easier to implement them when all 4 widgets are done, **however** the info is passed already to the respective chart component_
- Although the scope was to use mocked data, the data already exists in Strapi so I'm using it. 
https://skytruth-30x30-git-sky30-137-fe-implement-th-0120ce-vizzuality1.vercel.app//data-tool/NA
[SKY30-137 | FE - Implement the "Marine Conservation Protection Types" widget](https://vizzuality.atlassian.net/browse/SKY30-137)

[SKY30-137] FE - Implement the "Marine Conservation Protection Types" widget

---

infrastructure/base/main.tf
infrastructure/base/modules/bastion/main.tf

In order to try to prevent exceeding rate of requests when running data pipeline scripts, the max scale is now set to 2. The instance still has a cold start to prevent incurring cost when unused.
Added an ignore rule for bastion host metadata to prevent wiping out SSH keys added to the instance by data pipeline users.
---

Increase max backend CloudRun scale

---

frontend/src/containers/data-tool/content/map/sync-settings.ts

This PR loads by default eh EEZ and MAP layers if there are not any other layer set in the URL in the initial load of the page.
https://vizzuality.atlassian.net/browse/SKY30-143
---

[SKY30-143]: renders EEZ and MAP layers by default

---

frontend/src/containers/data-tool/content/details/tables/global-regional/index.tsx
frontend/src/containers/data-tool/content/details/tables/global-regional/useColumns.tsx

This PR allows the user to click on a _"Location"_ (data tool column) and be taken to that location. 
**Note:** This only applies to the national/regional tables. The national one displays protected areas, which we cannot link
[SKY30-136 | Data Tool tables first column should be clickable](https://vizzuality.atlassian.net/browse/SKY30-136)

[SKY30-136] Data Tool tables first column should be clickable

---

frontend/src/layouts/static-page.tsx

Fix the double border in the Privacy Policy and Terms of Service pages (below the header).
N/A

Fix double border below header on ToS and Privacy pages

---

frontend/src/containers/data-tool/content/map/popup/eez/index.tsx
frontend/src/containers/data-tool/sidebar/widgets/marine-conservation/index.tsx

- fixes the figure displayed in the EEZ popup to display correctly the same value calculated in the Marine Conservation Coverage widget. 
- fixes formatting of total area.
---

[N/A]: fixes way to calculate protected area in EEZ popup

---

frontend/src/pages/privacy-policy.tsx
frontend/src/pages/terms-of-use.tsx

This PR adds the shared existing CTAs to the ToS and Privacy Policy pages placeholders. 
N/A
(Orange ones)

[N/A] Add CTAs to ToS and Privacy pages

---

frontend/src/containers/data-tool/content/details/index.tsx
frontend/src/containers/data-tool/content/details/tables-settings.ts

Location code used to be `highSeas`, but got changed to `highseas`. 
Data table would fail to get the title.

[N/A] Fix ABNJ data table crash

---

frontend/src/containers/data-tool/content/details/tables/national-highseas/useTooltips.tsx

We need to display different tooltips for the data tables "Coverage" column, depending on whether the user is viewing the global/region table or the national/highseas one. The BE already added the new `coverage-wdpa` slug to the DataInfo table. 
N/A

[N/A] Change tooltip slug for the national/high-seas tables

---

frontend/src/containers/map/sidebar/index.tsx
frontend/src/pages/map/[locationCode].tsx

This PR fixes an issue on Safari/iOS in which the map sidebar doesn't render correctly on the first render.  
It looks like the issue are the animations, which are set for `absolute` positioning, yet the `div` had been set to `relative`. Because the `div` does need to be set to `relative` on mobile, I've added variants. 
**Note:**  
We still have some issues with the height of the app on tablets, due to the top bar; this would be addressed separately. 
Using Safari on iOS:  
- Open the website  
- Navigate to the map  
- Verify that:  
- The sidebar renders correctly
_See screenshots below for the issue_
**Before**
**After**
N/A

[N/A] Fixing sidebar not showing correctly on Safari

---

frontend/src/containers/map/content/map/index.tsx
frontend/src/containers/map/sidebar/widgets/index.tsx
frontend/src/pages/map/[locationCode].tsx

This PR fixes, _for real_, an issue while when 5 minutes goes by, revalidating the locations query would fail (reading `undefined`) as the cache wasn't being populated correctly at page level (`location` vs `{ data: location }`).
Only way to test this is leaving the page for 5 mins, and when the hook refetches the data again, everything should work as expected instead of "randomly" failing.
[N/A] Should fixed this reported issue: https://docs.google.com/document/d/1TuwDN8tgrD68epIuxqNwDx45F7E_gvvzIIaGw45VKzY/edit?disco=AAAA8zr4Usw
---

[N/A]: fixes location query cache

---

frontend/src/components/static-pages/intro/index.tsx
frontend/src/containers/homepage/intro/index.tsx
frontend/src/containers/homepage/link-cards/link-card/index.tsx

This PR fixes some components' display on Safari:  
- Homepage Intro  
- Homepage Link Cards 
_Services section_
- Static pages' Intro  
- About page  
- Knowledge Hub  
**Notes:**  
The task called for a fix for the link cards, I took the liberty to fix all similar components, hence why the Intros were done as well. 
[SKY30-178](https://vizzuality.atlassian.net/browse/SKY30-178)
[SKY30-178]: https://vizzuality.atlassian.net/browse/SKY30-178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SKY30-178] Fix Safari display (homepage intro, homepage link cards, about/knowledge hub intro)

---

frontend/src/containers/map/content/details/table/index.tsx

This PR removes the blue coverage bars from the table rows. 
They do not work correctly on Safari (and possibly Chrome on iOS). A proper fix for this bug (see [example on StackOverflow](https://stackoverflow.com/questions/64912199/safari-table-row-gradient-background-repeat-bug)) was not found in a timely manner, and it was agreed that the course to action would be to simply remove the bars (see feedback sheet)
[SKY30-191](https://vizzuality.atlassian.net/browse/SKY30-191)
[SKY30-191]: https://vizzuality.atlassian.net/browse/SKY30-191?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SKY30-191] Remove blue bar colors from table rows

---

frontend/src/components/widget/no-data/index.tsx

This PR changes the message displayed in a widget when data is not available for it, according to the Feedback sheet. 
Greece location produces such a message in the marine conservation protection types widget. 
[SKY30-184](https://vizzuality.atlassian.net/browse/SKY30-184)
[SKY30-184]: https://vizzuality.atlassian.net/browse/SKY30-184?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SKY30-184] Simplify the widget message when data is not available for it

---

frontend/src/containers/map/sidebar/details/widgets/habitat/index.tsx

This PR removes the _30% target_ from the Proportion of Habitat widget. 
[SKY30-182](https://vizzuality.atlassian.net/browse/SKY30-182)
[SKY30-182]: https://vizzuality.atlassian.net/browse/SKY30-182?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SKY30-182] Remove '30% target' from the Proportion of Habitat widget

---

frontend/src/components/footer.tsx
frontend/src/components/head/index.tsx
frontend/src/layouts/default.tsx
frontend/src/layouts/error-page.tsx
frontend/src/layouts/fullscreen.tsx
frontend/src/layouts/map.tsx
frontend/src/layouts/static-page.tsx

This PR changes every instance of the word _Skytruth_ to _SkyTruth_ (notice the capital _T_).  
In order to prevent further typos when creating new pages/layouts, a new `Head` component was added, instead of duplicating the code for every page/layout. 
[SKY30-197](https://vizzuality.atlassian.net/browse/SKY30-197)
[SKY30-197]: https://vizzuality.atlassian.net/browse/SKY30-197?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SKY30-197] Change every instance of the word skytruth to sky truth

---

frontend/src/containers/map/content/map/popup/eez/index.tsx

**NOTE: do NOT merge this PR until we have approval from data team.**
This PR updates the content of the EEZ popup to display the total of protected area instead of the total of marine area.
https://vizzuality.atlassian.net/browse/SKY30-185
---

[SKY30-185] eez popup: changes total area to protected area

---

frontend/src/containers/map/content/map/popup/eez/index.tsx
frontend/src/containers/map/content/map/popup/regions/index.tsx

Clicking on _Open country insights_ button in popup now fit bounds to the selected location and closes the popup.
https://vizzuality.atlassian.net/browse/SKY30-186
---

[SKY30-186]: closes popup and fit bounds on opening country insights

---

frontend/src/containers/map/content/map/popup/protected-area/index.tsx
frontend/src/containers/map/sidebar/details/widgets/marine-conservation/index.tsx
frontend/src/lib/utils/formats.ts

The Marine Conservation Coverage widget will now display the protected area instead of the total area. 
**Notes:**
- This widget now uses the `formatKM` helper to display the area  
- `maximumSignificantDigits` was removed from `formatKM` by default, as it was too restrictive. Because this utility was only used in _one_ place in the app, I've added the existing options to the call itself, in order not to change current behaviour. 
[SKY30-181](https://vizzuality.atlassian.net/browse/SKY30-181)
[SKY30-181]: https://vizzuality.atlassian.net/browse/SKY30-181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SKY30-181] Marine Conservation Coverage area should be the protected area, not the total area

---

frontend/src/containers/homepage/intro/index.tsx
frontend/src/containers/homepage/intro/sidebar-item/index.tsx

This PR is branched off https://github.com/Vizzuality/skytruth-30x30/pull/133 and should not be merged before. 
This PR changes the ocean protected area indicator on the homepage intro to have 1 decimal place, as per the feedback sheet, as well as updating the land area indicator which is hardcoded. 
[SKY30-177](https://vizzuality.atlassian.net/browse/SKY30-177)
[SKY30-177]: https://vizzuality.atlassian.net/browse/SKY30-177?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SKY30-177] Change the two top line indicators in the homepage to include one decimal place

---

frontend/src/components/charts/horizontal-bar-chart/index.tsx
frontend/src/containers/map/content/details/table/helpers.ts
frontend/src/containers/map/content/map/popup/protected-area/index.tsx
frontend/src/containers/map/sidebar/details/widgets/marine-conservation/index.tsx
frontend/src/lib/utils/formats.ts

This PR aims to fix the issues with https://github.com/Vizzuality/skytruth-30x30/pull/133, which didn't seem to work probably due to a bad rebase. I've opened a new branch and cherry-picked the respective commits.

Sky30 180 m 1 use one decimal place in the marine conservation coverage widget fix

---

frontend/src/containers/knowledge-hub/card-list/card-item/index.tsx

Displays full description of the card (in `/knowledge-hub`) on mouse hover.
https://vizzuality.atlassian.net/browse/SKY30-203
---

[SKY30-203] adds title attribute to display full description mouse hover

---

frontend/src/layouts/fullscreen.tsx
frontend/src/pages/contact.tsx

This PR addresses layout issues with the contact page. 
While investigating the ticket, I've noticed a mention about removing the bottom border. However, this border is part of the layout wrapper and not the cause of the visual issues; instead it was due to overflows. 
I've opted to re-implement the base layout for the Contact Page (didn't touch the components), in order to keep things consistent. In this way we approximate the page to the actual designs: 
- The bottom left image is now responsive and stuck to the bottom  
- Minor tweaks to the overall left/right columns spacing  
- Sidebar is now fixed (a requirement in order to keep the bottom left image displayed in a way that matches the designs)  
- Form no longer overflows; instead it is scrollable  
- No issues on mobile, nor in …

[SKY30-195] Rework base Contact page layout in order to eliminate screen size issues

---

cms/database/migrations/2024.01.19T10.00.00.change_data_tool_resource_type_relation_to_has_many.js
cms/src/api/data-tool/content-types/data-tool/schema.json
cms/types/generated/contentTypes.d.ts

Changed relation between data tool and resource type to has_many, using a strapi data migration in order not to lose data
---

Changed relation between data tool and resource type to has_many

---

cms/src/api/data-tool/content-types/data-tool/schema.json
cms/types/generated/contentTypes.d.ts

Temporarily add back 1-1 relationship for backwards compatibility

---

frontend/src/containers/map/content/details/index.tsx

A `location` variable was wrongly used (it wasn't even declared) as the linter gave green light because it was misunderstood with `window.location`.
This PR resolves an issue reported in [Slack](https://vizzuality.slack.com/archives/C056QHB3TML/p1705584935432589)
---

[N/A] fixes wrong location variable declaration

---

frontend/src/containers/map/content/details/index.tsx
frontend/src/containers/map/content/details/table/index.tsx
frontend/src/styles/globals.css

This PR fixes the details tables' header to the top on scroll. 
**Note:** 
It looks like `position: sticky` doesn't play very well when parent containers have an overflow set, so there was some trickery involved in order to make this work. The headers' borders wouldn't display on scroll either, hence the extra global. 
[SKY30-201](https://vizzuality.atlassian.net/browse/SKY30-201)
[SKY30-201]: https://vizzuality.atlassian.net/browse/SKY30-201?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SKY30-201] Fix details table headers on scroll

---

frontend/src/lib/utils/formats.ts

This PR implements a check when formatting percentages, to prevent the display of values over 100%. 
Visit the map, choose "Palau". 
Verify that, on the "Proportion of Habitat within Protected and Conserved Areas" widget, "Seamounts" is not over 100%.
[https://vizzuality.atlassian.net/browse/SKY30-189](https://vizzuality.atlassian.net/browse/SKY30-189)

[SKY30-189] Prevent the display of percentage values over 100%

---

frontend/package.json
frontend/src/components/tooltip-button/index.tsx
frontend/src/containers/map/content/details/table/tooltip-button/index.tsx
frontend/yarn.lock

This PR makes it so that links within info buttons/tooltips are clickable. 
This applies to:  
- Widgets / charts tooltips  
- Table column headers  
This is achieved by the `react-linkify` library. In addition, the details tables' column info buttons now make use of the global tooltip component, so that any related changes to this are applied app-wide. 
1. Visit the map page
2. On the _"Marine Conservation Coverage"_
- Verify the _"30x30 Target"_ Info button's link is clickable
3. On the _"Marine Conservation Protection Levels"_ bar charts
- Verify the info buttons' links are clickable
4. Open the details' table
- Verify that links are clickable in the table column headers' info buttons 
[SKY30-223](https://vizzuality.atlassian.net/browse/SKY30-223)
[SKY30-223]: …

[SKY30-223] Make links within info buttons/tooltips clickable

---

frontend/src/containers/map/content/map/popup/eez/index.tsx
frontend/src/containers/map/content/map/popup/regions/index.tsx

This PR fixes a couple issues in which the region popup percentage formatting does not match the formatting in the sidebar. In addition, it switches the area displayed to be the protected area, not the total one. 
**In this PR:**
- Use the `formatPercentage` and `formatKM` helpers in both _Regions_ and _EEZ_ popups, in order to keep the formatting consistent  
- Map regions tooltip now displays the protected area, not the total area
_Similar calculations as the ones used in the sidebar_  
- Changed the Regions tooltip button to say _Open region insights_ instead of _Open country insights_
1. Visit the map  
2. Choose _"Africa"_ region  
3. On the map, toggle all layers off except for the _"Regions"_ one  
4. Click on the highlighted Africa region on the map  
- Verify that the area and …

[SKY30-227] Check regions tooltip (area and decimals in %)

---

frontend/src/containers/map/sidebar/details/widgets/index.tsx

Ongoing work to adapt the dashboard to the new designs. 
Changes intended:  
- ~Add the new bar for the Fishing protection indicator~
_Note: There's a task [specific to this change](https://vizzuality.atlassian.net/browse/SKY30-226), so it won't be addressed by this PR_  
- Remove the Marine Conservation Establishment Stages widget
_Not intended to be in the Sidebar at this point; it's been commented out so we retain its code for a future stage_  
- ~Remove the 30% Target only in the _Proportion of Habitat within Protected and Conserved Areas_ widget~  
_Technically not addressed in this PR; it's been removed before. _
[SKY30-228](https://vizzuality.atlassian.net/browse/SKY30-228)
[SKY30-228]: https://vizzuality.atlassian.net/browse/SKY30-228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y …

[SKY30-228] M3 - Adapt dashboard to new design

---

frontend/src/containers/map/content/details/index.tsx
frontend/src/containers/map/sidebar/details/location-selector/index.tsx

This PR changes the dashboard's _"Change location"_ and details' _"Close"_ button font to overpass mono to match the rest of the website. In addition, the text size was better approximated to the designs. 
[SKY30-239](https://vizzuality.atlassian.net/browse/SKY30-239)
[SKY30-239]: https://vizzuality.atlassian.net/browse/SKY30-239?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SKY30-239] Change change location and close dashboard buttons font

---

frontend/src/containers/map/sidebar/index.tsx
frontend/src/styles/globals.css

This PR increases the map sidebar width slightly, to better match the designs and prevent a clash between the _Highly protected from fishing_ indicator in the _Marine Conservation Protection Levels_ widget. 
N/A

[N/A] Increase the sidebar width slightly

---

frontend/src/containers/homepage/intro/index.tsx
frontend/src/pages/index.tsx

This PR makes it so that all remaining static indicators displayed in the homepage are pulled from the CMS, including the Intro ones. 
[SKY30-218](https://vizzuality.atlassian.net/browse/SKY30-218)
[SKY30-218]: https://vizzuality.atlassian.net/browse/SKY30-218?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SKY30-218] Ensure consistency across indicators

---

frontend/src/components/ui/button.tsx
frontend/src/containers/map/sidebar/details/details-button/index.tsx
frontend/src/containers/map/sidebar/details/index.tsx

- When the details tables are open, we no longer display the small back arrow (instead we keep the _"Marine Conservation Details"_ button visible  
- _"Marine Conservation Details"_ styling changes to better match the designs  
- Centered text  
- No arrow / chevron  
- Height to _40px_  
- Decreased font size  
[SKY30-244](https://vizzuality.atlassian.net/browse/SKY30-244)
[SKY30-244]: https://vizzuality.atlassian.net/browse/SKY30-244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SKY30-244] Remove blue arrow when the details tables are open + styling changes

---

frontend/src/hooks/use-scroll-spy.ts
frontend/src/layouts/static-page.tsx
frontend/src/pages/about/index.tsx
frontend/src/pages/index.tsx

This PR highlights the side navigation based on the active section for the home and about pages.   
[SKY30-241](https://vizzuality.atlassian.net/browse/SKY30-241)
[SKY30-241]: https://vizzuality.atlassian.net/browse/SKY30-241?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SKY30-241] Highlight side navigation active section item on the home and about pages

---

frontend/src/containers/map/sidebar/index.tsx

This PR adjusts the button that closes the map sidebar to match the height of the blue buttons next to it. 
[SKY30-275](https://vizzuality.atlassian.net/browse/SKY30-275)
[SKY30-275]: https://vizzuality.atlassian.net/browse/SKY30-275?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SKY30-275] Close sidebar button to be the same height as the blue buttons next to it

---

frontend/src/components/ui/collapsible.tsx
frontend/src/containers/map/content/map/layers-toolbox/index.tsx
frontend/src/containers/map/content/map/layers-toolbox/layers-list/index.tsx
frontend/src/containers/map/content/map/layers-toolbox/legend/index.tsx
frontend/tailwind.config.js

This PR makes it so that the legend items are open by default. 
- Legend items are open by default  
- Because which items are open is tied to the sync settings, and in order to prevent applying sync settings on load for performance and maintainability reasons, the code first checks whether we have settings. If not all items are open by default. If yes, it's not a first load, so sync settings are respected  
- Same logic as above is implemented for when the user toggles a layer on  
- Added an animation to the Collapsible component
- So that both legend and layers tabs have similar animations
- Dropdown/Accordion arrows now display similar behaviours as well 
[SKY30-258](https://vizzuality.atlassian.net/browse/SKY30-258)
[SKY30-258]: …

[SKY30-258] Legend items open by default

---

frontend/src/containers/map/content/details/tables/global-regional/index.tsx
frontend/src/containers/map/content/details/tables/global-regional/useColumns.tsx

This PR makes it so that the global/regional tables display the protected area and not the total area (in the area column). 
It also adds a check to ensure that, due to rounding, the protected area does not exceed the total marine area (which can happen when coverage is near 100%). 
This PR includes commits from #197 , which should be merged first. 
This was to prevent code conflicts. 
[SKY30-279](https://vizzuality.atlassian.net/browse/SKY30-279)
[SKY30-279]: https://vizzuality.atlassian.net/browse/SKY30-279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SKY30-279] Global/regional tables to display the protected area and not the total area in the area column

---

infrastructure/base/vars/terraform.tfvars

Staging instance is now at https://30x30-dev.skytruth.org/
Production will be at https://30x30.skytruth.org/
https://vizzuality.atlassian.net/browse/SKY30-296?atlOrigin=eyJpIjoiZTA2NGM3OTBjMTdlNDQzZDg1M2EzZDc4MjhiN2I5NDUiLCJwIjoiaiJ9
---

Set the new staging subdomain

---

frontend/src/components/charts/conservation-chart/index.tsx
frontend/src/components/charts/conservation-chart/tooltip/index.tsx
frontend/src/containers/map/sidebar/details/widgets/marine-conservation/index.tsx
frontend/src/pages/_app.tsx

- Calculations re-done to the conservation chart  
- Aligned the 30x30 target tooltip button for the coverage chart  
- Enabled tooltips to the yearly columns (bars only)
[SKY30-256](https://vizzuality.atlassian.net/browse/SKY30-256)
[SKY30-256]: https://vizzuality.atlassian.net/browse/SKY30-256?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SKY30-256] Add tooltips of the yearly data for the column chart in dashboards

---

frontend/src/containers/map/content/details/table/helpers.ts
frontend/src/containers/map/content/details/tables/global-regional/index.tsx
frontend/src/containers/map/content/details/tables/global-regional/useColumns.tsx

This PR makes it so that the same area formatter is used across the app, for consistency purposes. 
**Notes:** 
- This PR also reverts the check that ensures an area displayed in the details tables does not exceed the total marine area  
- This is no longer applicable  
- There's some discussion going on about how to deal with values too close to 0 (which would get rounded to 0) as well as upper values  
- This is out of scope, but related. 
[SKY30-298](https://vizzuality.atlassian.net/browse/SKY30-298)
[SKY30-298]: https://vizzuality.atlassian.net/browse/SKY30-298?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SKY30-298] Standardize area format across the platform

---

frontend/package.json
frontend/src/components/charts/horizontal-bar-chart/index.tsx
frontend/src/lib/utils/formats.ts
frontend/yarn.lock

Some areas are smaller than 1 km2 and due to rounding are displayed as 0 km2. 
This PR tweaks the formatKM function to display areas smaller than 1 km2 as "<1 km2", similar to how percentages are dealt with. 
[SKY30-300](https://vizzuality.atlassian.net/browse/SKY30-300)
[SKY30-300]: https://vizzuality.atlassian.net/browse/SKY30-300?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SKY30-300] Display 1 km 2 for areas smaller than 1 but bigger than 0

---

frontend/src/components/filters-button/index.tsx
frontend/src/components/static-pages/section/index.tsx
frontend/src/containers/knowledge-hub/card-filters/index.tsx
frontend/src/containers/knowledge-hub/card-filters/resource-types/index.tsx
frontend/src/containers/knowledge-hub/card-list/index.tsx
frontend/src/containers/knowledge-hub/store.ts
frontend/src/layouts/static-page.tsx
frontend/src/pages/knowledge-hub.tsx

This PR moves away the resource types selector from the title to fit along the rest of filters.
Also, this PR addresses:
- fixed loop produced when some filters where applied and the user clicked on _clear filters_ button producing a loop of re-renders. 
- adjusts some margins of the page/containers to be consisntent.
https://www.figma.com/file/RQB86KnkGg4UTpqQZ09KBX/30x30-Design-%5BInternal%5D?node-id=2249%3A9160&mode=dev
https://vizzuality.atlassian.net/browse/SKY30-325
---

[SKY30-325] knowledge hub: multiple resource types

---

frontend/src/containers/map/sidebar/main-panel/details/index.tsx
frontend/src/containers/map/sidebar/main-panel/details/location-selector/location-dropdown/index.tsx

Fixes an issue where the location selected when there was no location code in the URL was random (it depended on the way the API was returning the list as we were always asking for the first location). Now we make sure if there is no location code present, `GLOB` is the default.
https://vizzuality.atlassian.net/browse/SKY30-337
---

[SKY30-337] fixes initial location without location code

---

frontend/src/containers/map/content/map/index.tsx
frontend/src/containers/map/content/map/popup/index.tsx

Additionally, adds a listener to close the popup when the user presses the `Escape` key.
https://vizzuality.atlassian.net/browse/SKY30-334
---

[SKY30-334] displays EEZ names hovering the map

---

frontend/src/constants/fishing-protection-chart-colors.ts
frontend/src/constants/protection-types-chart-colors.ts
frontend/src/containers/map/sidebar/main-panel/details/widgets/fishing-protection/index.tsx
frontend/src/containers/map/sidebar/main-panel/details/widgets/index.tsx
frontend/src/containers/map/sidebar/main-panel/details/widgets/protection-types/index.tsx

This PR splits the Protection Levels widget into two: 
- Marine Conservation **Protection Levels** 
- **Fishing Protection**  
The new widget is simply a duplicate of the first, to make things easier, with: 
- Relevant parameters from the query removed  
- New color for the chart  
The original support for adding new entries and setting colors has been preserved, both for speeding up the task and to make it easier in case we revert and/or add new entries to the widget in the future. 
[SKY30-343](https://vizzuality.atlassian.net/browse/SKY30-343)
[SKY30-343]: https://vizzuality.atlassian.net/browse/SKY30-343?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SKY30-343] Split Protection Levels widget into two  

---

frontend/src/components/charts/horizontal-bar-chart/index.tsx
frontend/src/constants/habitat-chart-colors.ts

- Updated the proportion of habitat widget's bar colors to match the design 
- added the word “out” in the label below each habitat percentage for example “out of 149,887 km2" 
_Note: as of now this would apply to the other widgets as well, but I believe this should be addressed when addressing [SKY30-280](https://vizzuality.atlassian.net/browse/SKY30-280)_
[SKY30-344](https://vizzuality.atlassian.net/browse/SKY30-344)
[SKY30-344]: https://vizzuality.atlassian.net/browse/SKY30-344?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SKY30-280]: https://vizzuality.atlassian.net/browse/SKY30-280?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SKY30-344] Habitats widget changes

---

frontend/src/components/widget/index.tsx
frontend/src/containers/map/content/details/index.tsx
frontend/src/containers/map/content/details/tables/global-regional/index.tsx
frontend/src/containers/map/content/details/tables/national-highseas/index.tsx
frontend/src/containers/map/content/map/layer-manager/item.tsx
frontend/src/containers/map/sidebar/main-panel/details/index.tsx
frontend/src/containers/map/sidebar/main-panel/details/location-selector/index.tsx
frontend/src/containers/map/sidebar/main-panel/details/location-selector/location-dropdown/index.tsx
frontend/src/containers/map/sidebar/main-panel/details/widgets/index.tsx
frontend/src/containers/map/sidebar/main-panel/modelling/widget/index.tsx
frontend/src/pages/progress-tracker/[locationCode].tsx

This PR defaults the `locationCode` to `GLOB` when using `useRouter` or `useParams` throughout the app. This was the (working) solution implemented to solve some of the bugs. 
I think there has to be a better way though. 
**Note:** there are some extra changes due to linting errors I saw. 
The bug doesn't seem to exhibit locally; in order to reproduce it locally I had to run a production build. 
[https://vizzuality.atlassian.net/browse/SKY30-350](https://vizzuality.atlassian.net/browse/SKY30-350)

[SKY30-350] Fix for incorrect data when locationCode in the query doesn't exist

---

frontend/src/components/charts/conservation-chart/index.tsx
frontend/src/components/charts/conservation-chart/legend/index.tsx
frontend/src/components/widget/index.tsx
frontend/src/containers/map/sidebar/main-panel/details/widgets/establishment-stages/index.tsx
frontend/src/containers/map/sidebar/main-panel/details/widgets/fishing-protection/index.tsx
frontend/src/containers/map/sidebar/main-panel/details/widgets/habitat/index.tsx
frontend/src/containers/map/sidebar/main-panel/details/widgets/marine-conservation/index.tsx
frontend/src/containers/map/sidebar/main-panel/details/widgets/protection-types/index.tsx
frontend/src/containers/map/sidebar/main-panel/details/widgets/useTooltips.ts

- Marine Conservation Coverage widget changes
- Small color changes to the header  
- Text sizing changed to the text displayed below the title  
- Small change to the text displayed below the title  
- Chart colors change  
- 30% target only displayed for GLOB  
- Added tooltips next to the widgets title 
**Note:**  
About the Tooltips button next to the widgets title, I followed the pattern in other components. I think this should be simplified, mostly due to the multiple instances of the `useTooltips` hooks, but in the future as part of a go at code tidying. I did start revamping this but it looked like it would take longer than expected, and because of the timeframe and possibility of introducing even more bugs this should probably be addressed as a chore in the …

[SKY30-342] Marine conservation coverage widget changes

---

frontend/src/containers/map/content/map/popup/eez/index.tsx
frontend/src/containers/map/content/map/popup/regions/index.tsx

Adds total area to EEZ and Regions popups. Also, updates color from blue to black according to design.
https://www.figma.com/file/RQB86KnkGg4UTpqQZ09KBX/30x30-Design-%5BInternal%5D?node-id=2371%3A13002&mode=dev
https://vizzuality.atlassian.net/browse/SKY30-333
---

[SKY30-333] adds total area to EEZ and Regions popups

---

frontend/src/containers/map/content/details/table/index.tsx
frontend/src/containers/map/content/details/table/sorting-button/index.tsx

This PR sets the default sorting on tables so that the first column is ordered alphabetically (in ascending order) by default. 
It also fixes the asc/desc icons being flipped. 
[SKY30-318](https://vizzuality.atlassian.net/browse/SKY30-318)
[SKY30-318]: https://vizzuality.atlassian.net/browse/SKY30-318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SKY30-318] Update default sort of tables to be alphabetical

---

frontend/src/components/charts/horizontal-bar-chart/index.tsx
frontend/src/components/tooltip-button/index.tsx
frontend/src/components/widget/index.tsx
frontend/src/containers/map/sidebar/main-panel/details/widgets/establishment-stages/index.tsx
frontend/src/containers/map/sidebar/main-panel/details/widgets/fishing-protection/index.tsx
frontend/src/containers/map/sidebar/main-panel/details/widgets/habitat/index.tsx
frontend/src/containers/map/sidebar/main-panel/details/widgets/marine-conservation/index.tsx
frontend/src/containers/map/sidebar/main-panel/details/widgets/protection-types/index.tsx

- Redesigns a little the distribution of elements inside the widgets.
- Adds total area to widgets along with the current protected area.
- Adds sources inside tooltip buttons.
https://vizzuality.atlassian.net/browse/SKY30-305
https://vizzuality.atlassian.net/browse/SKY30-341
https://vizzuality.atlassian.net/browse/SKY30-353
---

[SKY30-305/SKY30-341SKY30-353]widget redesign and sources implementation

---

frontend/src/components/header.tsx

Fixes _Progress tracker_ item broken in Safari
https://vizzuality.atlassian.net/browse/SKY30-361
---

[SKY30-361] Safari: fixes menu item break into two rows

---

frontend/src/containers/map/content/details/tables/national-highseas/index.tsx
frontend/src/containers/map/content/details/tables/national-highseas/useFiltersOptions.ts

Also, fixes filtering when the user _selects all_
https://vizzuality.atlassian.net/browse/SKY30-362
---

[SKY30-362]: hides internal protection levels & fixes select all filtering

---

frontend/src/containers/map/sidebar/main-panel/details/widgets/protection-types/index.tsx

Hides _target 30x30_ label in Marine Conservation Protection Levels widget.
https://vizzuality.atlassian.net/browse/SKY30-365
---

[SKY30-365]: hides show target label in marine conservation widget

---

frontend/src/containers/map/content/map/index.tsx
frontend/src/containers/map/sidebar/main-panel/details/location-selector/index.tsx

As it turns out, the map will not zoom into a selected country when clicking on a country in the list displayed on the sidebar header (eg: when location is selected to Africa region, the list of countries that is displayed). 
I've noticed that in the current implementation, when a user selects a location in the location selector, the bbox is set there, and then a new location is pushed via router. In other places, we're using a next/link. 
The change made here, was to make it so that the map will respond to location param changes, which would make the map zoom in into the selected location in all scenarios. 
[SKY30-358](https://vizzuality.atlassian.net/browse/SKY30-358)
[SKY30-358]: https://vizzuality.atlassian.net/browse/SKY30-358?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRk …

[SKY30-358] Map to respond to location changes and update bbox accordingly

---

frontend/src/containers/map/sidebar/main-panel/details/widgets/protection-types/index.tsx

This task was addressed [previously](https://github.com/Vizzuality/skytruth-30x30/commit/cae6960fc12d1d04f638afdef8f1916fecb7bd8b) but looks like [the criteria was wrong](https://vizzuality.atlassian.net/browse/SKY30-365?focusedCommentId=29307) so I am updating it.
https://vizzuality.atlassian.net/browse/SKY30-365
---

[SKY30-365] marine conservation widget: show target only for global view

---

frontend/src/containers/map/content/details/tables/national-highseas/index.tsx
frontend/src/containers/map/content/details/tables/national-highseas/useColumns.tsx
frontend/src/containers/map/content/details/tables/national-highseas/useFiltersOptions.ts

- adds `N/A` fallback for `undefined` values. 
- adds a `N/A` option to Establishment Stage filter to be able to filter by this new value.
https://vizzuality.atlassian.net/browse/SKY30-367
---

[SKY30-367] adds N/A fallback and filter option for establishment stage column

---

frontend/src/containers/map/content/map/popup/eez/index.tsx
frontend/src/containers/map/content/map/popup/generic/index.tsx
frontend/src/containers/map/content/map/popup/item.tsx
frontend/src/containers/map/content/map/popup/protected-area/index.tsx
frontend/src/containers/map/content/map/popup/regions/index.tsx

This PR modifies the behavior of the EEZ layer popup slightly: 
- when clicking on a conflict zone (like Maldivas), if the user is in the global view, it will not show any data
- if the case of Maldivas, if the user has Argentina selected, clicking on Maldivas will show the same percentage of protected areas as Argentina.
- if the case of Maldivas, if the user has United Kingdom selected, clicking on Maldivas will show the same percentage of protected areas as United Kingdom.
This behavior should apply to any conflictive zone.
–
---

[N/A] EEZ popup: deal with conflict zones

---

frontend/src/lib/utils/formats.ts

This PR makes it so that percentages always display a decimal place, even if it's zero. 
This is done for consistency purposes, so it was done in the formatter and changes will be reflected anywhere in the app (with an exception for values stored in Strapi which is the case for many values in the static pages, in which case they have to be updated manually, as usual). 
[SKY30-376](https://vizzuality.atlassian.net/browse/SKY30-376)
[SKY30-376]: https://vizzuality.atlassian.net/browse/SKY30-376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SKY30-376] Percentages to always display one decimal place (even if it's 0)

---

frontend/src/containers/map/sidebar/main-panel/details/widgets/protection-types/constants.ts
frontend/src/containers/map/sidebar/main-panel/details/widgets/protection-types/index.tsx

Frontend is using the `updatedAt` value from the protection levels data, instead of using the one from the mpaa protection level stats. This PR aims to fix that. 
**Notes:**  
- Commented out / obsolete code was removed  
In the past the widget displayed other protection level data besides the mpaa stats. While the call remains the same (in case we need to change it back in the future), the obsolete/commented out code was removed. Most of the functions retain the functionality to deal with extra protection levels.   
- Improve how the frontend is dealing with the names of the different protection levels  
We are not displaying the names returned by the endpoint; there are slight tweaks to them. In order to promote support for multiple protection levels (although we are only showing one …

[SKY30-377] Marine Conservation Protection Levels to display the correct last update data

---

frontend/src/pages/knowledge-hub.tsx

This PR removes the _"Data tools"_ from the Knowledge hub title
[SKY30-370](https://vizzuality.atlassian.net/browse/SKY30-370)
[SKY30-370]: https://vizzuality.atlassian.net/browse/SKY30-370?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SKY30-370] Remove 'Data tools.' from the knowledge hub title

---

frontend/src/components/active-link.tsx

This PR fixes the header links no longer displaying the "active" icon, when a static page is selected. 
The issue was introduced in #264, specifically in the inclusion of [this code](https://github.com/Vizzuality/skytruth-30x30/pull/264/files#diff-b50fc27f55e5446e9e46c6d2e3f9558139210f0c46acda75e4dafdb1b2711ba4R87-R102) in order to pass settings via links while hiding them from the user. 
**Note:** This PR was also tested for when we have the language in the url (eg: https://skytruth-30x30-git-sky30-383-header-links-no-45f06c-vizzuality1.vercel.app/fr/knowledge-hub)
1. Use the header links to navigate to a static page (eg: _Knowledge Hub_, _About_, _Contact_)  
2. Ensure a colorful arrow is displayed next to the link corresponding to the active static page …

[SKY30-383] Fix header links for static pages no longer displaying the "active" page arrow

---

frontend/src/containers/map/sidebar/main-panel/panels/details/widgets/protection-types/constants.ts
frontend/src/containers/map/sidebar/main-panel/panels/details/widgets/protection-types/index.tsx

This PR changes the API call so that we fetch data from the `MpaaProtectionLevelStats` endpoint (and populate what we need, `Location` and `MpaaProtectionLevel`), instead of querying the `Location` endpoint. 
The reasoning for this "fix" is because after the last data update, the associations in Strapi have changed populating the stats from the location endpoint no longer works (whether intended or a bug, the associations are just not there). This is a quick fix so we get the widget back online quickly. 
An added benefit, is that with this change we reduce the nesting in the query and simplify parsing the data a little bit. It will also make it easier to localize the entries. 
[SKY30-423](https://vizzuality.atlassian.net/browse/SKY30-423)
[SKY30-423]: …

[SKY30-423] Marine Conservation Protection Levels not working

---

frontend/src/containers/map/content/details/tables/national-highseas/index.tsx
frontend/src/containers/map/content/details/tables/national-highseas/useColumns.tsx

Map thumbnails are being problematic and client wants to hide them. 
Development team still hasn't gone through all the possibilities, so a middle ground was discussed:  
- We retain the code  
- We retain all the functionality  
- We comment out the column code for when we revisit this once we have more capacity  
**Notes:**  
- Any processing related to this task has been commented with the same comment, so it's easier for future developers (us) to find it and revert it. 
[SKY30-422](https://vizzuality.atlassian.net/browse/SKY30-422)
[SKY30-422]: https://vizzuality.atlassian.net/browse/SKY30-422?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SKY30-422]Hide layer preview data from details columns

---

frontend/src/containers/map/content/details/helpers.ts

This PR makes sure that when filters are applied to the tables, the sub rows are also consequently filtered.
1. Open `/progress-tracker/ABNJ`
2. Open the table view
3. Filter the table so that some sub rows would be filtered out
4. Filter the table so that some sub rows match the filters even if the main rows don't
[SKY30-433](https://vizzuality.atlassian.net/browse/SKY30-433)
[SKY30-433]: https://vizzuality.atlassian.net/browse/SKY30-433?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Take sub rows into account when filtering in the tables

---

frontend/src/containers/map/content/details/tables/national-highseas/useColumns.tsx

The “Type” column of the “Areas Beyond National Jurisdiction” table was empty for the rows for which the data comes from MPAtlas. Instead of displaying empty cells, this PR fallbacks to displaying `-`.
1. Open the table on `/progress-tracker/ABNJ`
2. Open the sub rows
[SKY30-435](https://vizzuality.atlassian.net/browse/SKY30-435)
[SKY30-435]: https://vizzuality.atlassian.net/browse/SKY30-435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Display fallback for the “Type” column in the “Areas Beyond National Jurisdiction” table

---

frontend/src/containers/map/sidebar/main-panel/panels/details/widgets/fishing-protection/index.tsx
frontend/src/containers/map/sidebar/main-panel/panels/details/widgets/index.tsx
frontend/translations/en.json

This PR adds back the Fishing Protection widget and uses the latest model changes that include the percentage of protected area. The total area provided by the “Location” model is not used anymore.
The request to Strapi is unnecessarily convoluted because of limitations to the way Strapi handles relations between localised and non-localised models. I added comments in the code to explain this.
[SKY30-441](https://vizzuality.atlassian.net/browse/SKY30-441)
[SKY30-441]: https://vizzuality.atlassian.net/browse/SKY30-441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add the Fishing Protection widget back

---

cms/config/api.ts

This PR increases the maximum number of rows returned by Strapi to 100 000 in order to make sure that all the protected areas of a country are listed in the details table.
The number 100 000 is arbitrary but we already know that we'll have up to 26k rows when all the terrestrial data is ingested.
Open the details table of France. Using the staging API, 475 rows should be rendered in the table.
[SKY30-447](https://vizzuality.atlassian.net/browse/SKY30-447)
[SKY30-447]: https://vizzuality.atlassian.net/browse/SKY30-447?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Allow Strapi to return more rows at once (up to 100 000)

---

frontend/src/containers/map/content/details/table/index.tsx
frontend/src/containers/map/content/details/tables/global-regional/useColumns.tsx
frontend/src/containers/map/content/details/tables/national-highseas/useColumns.tsx

This PR ensures that accented strings (à, é, è, etc.) are correctly sorted in the tables according to their locale. The PR makes use of `String.prototype.localeCompare()` to perform the sort.
1. Open the country profile of France
2. Open the details table
The names of the protected areas that start with an accent should be located next to the areas that don't have an accent. For example, «Étang» should be located close to «Etang».
[SKY30-448](https://vizzuality.atlassian.net/browse/SKY30-448)
[SKY30-448]: https://vizzuality.atlassian.net/browse/SKY30-448?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Correctly sort accented strings in tables

---

cms/config/sync/core-store.plugin_content_manager_configuration_content_types##api##protection-coverage-stat.protection-coverage-stat.json
cms/config/sync/user-role.public.json
frontend/src/components/charts/conservation-chart/index.tsx
frontend/src/constants/habitat-chart-colors.ts
frontend/src/containers/map/content/details/tables/global-regional/index.tsx
frontend/src/containers/map/sidebar/main-panel/location-selector/index.tsx
frontend/src/containers/map/sidebar/main-panel/panels/details/index.tsx
frontend/src/containers/map/sidebar/main-panel/panels/details/widgets/fishing-protection/index.tsx
frontend/src/containers/map/sidebar/main-panel/panels/details/widgets/habitat/index.tsx
frontend/src/containers/map/sidebar/main-panel/panels/details/widgets/marine-widgets.tsx
frontend/src/containers/map/sidebar/main-panel/panels/details/widgets/summary-widgets.tsx
frontend/src/containers/map/sidebar/main-panel/panels/details/widgets/terrestrial-conservation/index.tsx
frontend/src/containers/map/sidebar/main-panel/panels/details/widgets/terrestrial-widgets.tsx
frontend/src/hooks/use-scroll-position.ts
frontend/translations/en.json

This PR does a few things:
- Display the terrestrial widgets in the sidebar
- Make sure the marine widgets only pull marine data
- Collapse/expand the sidebar's header based on the scroll position
- Use your local database as this PR is based on the terrestrial branch that has a different database schema
- Comment the LOCALAZY_CDN environment variable in your local .env to see the source strings (they are not uploaded to the CDN)
- The widgets will appear empty unless you link the stats models to the Environment model as we're filtering them by environment
[SKY30-388](https://vizzuality.atlassian.net/browse/SKY30-388)
[SKY30-388]: https://vizzuality.atlassian.net/browse/SKY30-388?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Complete the sidebar with the terrestrial widget

---

frontend/src/containers/map/sidebar/main-panel/panels/details/widgets/fishing-protection/index.tsx
frontend/translations/en.json

This PR implements a few tweaks to the recently brought back Fishing Protection widget:  
- Renamed the widget to "Level of Fishing Protection" in the strings  
- I've temporarily renamed the original string in Localazy as well, for QA purposes  
- Removed the widget's info button  
- Deleted the respective API request as well for cleanup purposes  
- Removed the "30% target" orange indicator from the widget's entries  
- Added a check to prevent the display of `NaN`  
- In this particular scenario, it happens because both area and pct in the stats are 0, so there was a division by 0. 
- I've added a quick check for that, and when parsing data, we'll return `null` instead. The main function that parses the data will filter entries to eliminate `null` ones. In the particular bug scenario, …

[SKY30-450] Fishing protection level widget changes 

---

frontend/src/containers/map/sidebar/layers-panel/index.tsx
frontend/src/containers/map/sidebar/layers-panel/layers-group/index.tsx
frontend/translations/en.json

**In this PR:**   
- Layers panel now supports displaying three groups of layers (Terrestrial, Maritime, Basemap)  
- Each group of layers is independently collapsible   
- Collapsing/expanding of groups is synced with the corresponding tab selected in the sidebar   
- When a group is collapsed, the number of active layers within that group is displayed next to the group name  
- Implemented a "Loading data..." and "Data not available" mimicking how widgets behave when fetching/displaying data  
**Notes:**  
This PR doesn't connect to the new/in-progress endpoint with the new layer definitions. It focuses on the visual implementation as well as syncing with the recent work done for the sidebar. In order to display data for testing, the "original" endpoint is being used. …

[SKY30-444] Rework layers panel to support the three modes

---

frontend/src/components/widget/no-data/index.tsx
frontend/translations/en.json

This PR replaces the default “no data” message from “Data not available” to “No data available”.
[SKY30-431](https://vizzuality.atlassian.net/browse/SKY30-431)
[SKY30-431]: https://vizzuality.atlassian.net/browse/SKY30-431?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Replace the default “no data” widget message

---

frontend/src/components/widget/index.tsx
frontend/src/components/widget/no-data/index.tsx
frontend/src/containers/map/content/map/modelling/index.tsx
frontend/src/containers/map/sidebar/main-panel/panels/details/widgets/protection-types/index.tsx
frontend/src/containers/map/sidebar/main-panel/panels/modelling/widget/index.tsx
frontend/src/containers/map/store.ts
frontend/translations/en.json

This PR replaces the default “No data available” message displayed on the “Marine Conservation Protection Levels” widget by “Not assessed” when there is no data available.
[SKY30-417](https://vizzuality.atlassian.net/browse/SKY30-417).
[SKY30-417]: https://vizzuality.atlassian.net/browse/SKY30-417?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Change the “no data” message on the “Marine Conservation Protection Levels” widget

---

frontend/src/containers/map/sidebar/main-panel/location-selector/location-dropdown/index.tsx

When using the location selector on the sidebar, searching for a country returns unexpected results. 
An example is that, when the user types `uru` in the search box, looking for `Uruguay`, most of the search results return entries that do not have `uru` in the name. Uruguay does appear in the list, but the user will only see it if they scroll down. 
This PR provides a very simple, custom filtering function that is passed to the component (built with the `cmdk` library), in which it'll check whether the searched characters against the list (in a case insensitive way), so that the library will only show countries that _do_ include those characters. 
No external libraries added (eg: fusejs) as we don't have a need for fuzzy search at this point, and it'd introduce complexity, as we'd be …

[SKY30-452] Custom filtering when using the location input search in the sidebar

---

cms/config/sync/admin-role.strapi-super-admin.json
cms/config/sync/core-store.plugin_content_manager_configuration_content_types##api##location.location.json
cms/src/api/location/content-types/location/schema.json
cms/types/generated/contentTypes.d.ts
frontend/src/components/charts/conservation-chart/index.tsx
frontend/src/containers/map/sidebar/main-panel/panels/details/widgets/marine-conservation/index.tsx
frontend/src/containers/map/sidebar/main-panel/panels/details/widgets/terrestrial-conservation/index.tsx
frontend/src/types/generated/strapi.schemas.ts
frontend/translations/en.json

This PR makes a few changes to the “Marine Conservation Coverage” widget:
- Add two new fields to the Location model: `marine_target` and `marine_target_year`
- On the marine tab:
- Conditionally show the target if `marine_target` is not empty
- Replace the text on top of the target line from “30x30 Target” to “XX% target”
- Replace the content of the info button's tooltip to include the actual target and target year based on the new Strapi fields. If missing, default to 30% by 2030.
- [SKY30-403](https://vizzuality.atlassian.net/browse/SKY30-403)
- [SKY30-459](https://vizzuality.atlassian.net/browse/SKY30-459)
[SKY30-403]: https://vizzuality.atlassian.net/browse/SKY30-403?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SKY30-459]: …

Update the target on the conservation widget

---

frontend/src/constants/datasets.ts
frontend/src/constants/environments.ts
frontend/src/containers/map/sidebar/layers-panel/index.tsx
frontend/src/containers/map/sidebar/layers-panel/layers-group/index.tsx
frontend/translations/en.json

This PR connects the layers panel to the actual data coming from Strapi, and displays layers by environment type based on which environment a layer is currently assigned to. 
Changes were planned to be unobtrusive, and confined to the `LayersPanel` component that fetches datasets; it fetches datasets basically the same way as before, though it does populate the `environment` for the `layers` content type, and then processes them for display. The `LayersGroup` component is then kept unchanged. 
**Logic:**  
- Datasets are pulled in the same way as before, but now `environment` is populated as well  
- Datasets are parsed into 3 groups for display  
- Basemap (which is environment agnostic, but it is defined as a dataset group in Strapi)  
- On the display, we are injecting the `Labels` as …

Layers panel to display datasets grouped by environment - connect to Strapi

---

frontend/src/containers/map/content/map/index.tsx
frontend/src/containers/map/content/map/popup/eez/index.tsx
frontend/src/containers/map/content/map/popup/regions/index.tsx
frontend/src/containers/map/sidebar/main-panel/panels/details/index.tsx
frontend/src/containers/map/store.ts
frontend/src/lib/utils/geo.ts

This PR makes sure that when the user changes tab (Summary, Terrestrial, Marine), the map is zoomed to the extent of both the terrestrial and marine bounds, the terrestrial bounds and the marine bounds respectively.
[SKY30-476](https://vizzuality.atlassian.net/browse/SKY30-476)
[SKY30-476]: https://vizzuality.atlassian.net/browse/SKY30-476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Zoom to the correct bounds depending on the environment

---

frontend/src/containers/map/sidebar/main-panel/panels/details/widgets/habitat/index.tsx
frontend/src/containers/map/sidebar/main-panel/panels/details/widgets/summary-widgets.tsx

This PR makes sure to hide habitats with no associated data in the “Proportion of Habitat within Protected and Conserved Areas” widget. There is also a fix for a crash when changing location while viewing the Summary tab.
[SKY30-482](https://vizzuality.atlassian.net/browse/SKY30-482)
[SKY30-482]: https://vizzuality.atlassian.net/browse/SKY30-482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Hide habitats with no associated data in the habitat widget

---

frontend/src/containers/map/content/map/layers-toolbox/legend/index.tsx

This PR makes sure to only show relevant layers in the legend based on the active sidebar tab.
[SKY30-480](https://vizzuality.atlassian.net/browse/SKY30-480)
[SKY30-480]: https://vizzuality.atlassian.net/browse/SKY30-480?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Only show relevant layers in the legend

---

frontend/src/containers/map/sidebar/layers-panel/index.tsx

This PR makes sure that that layers on the map are only reset to the default ones when the tab changes. Before this, the layers would be reset when collapsing/expanding the layers panel.
[SKY30-481](https://vizzuality.atlassian.net/browse/SKY30-481)
[SKY30-481]: https://vizzuality.atlassian.net/browse/SKY30-481?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Only reset to the default layers when the tab changes

---

cms/src/api/pa/controllers/pa.ts
frontend/src/containers/map/content/details/table/helpers.ts
frontend/src/containers/map/content/details/tables/national-highseas/hooks.tsx
frontend/src/lib/utils/formats.ts

This PR applies internal feedback after the implementation of the paginated tables and the addition of the terrestrial data. In particular, this PR does the following:
- Make sure that the “Coverage” values are displayed as “<0.1%” if equal to 0 in Strapi
- Remove the “Data Source” filter when viewing the Terrestrial tab
- Fix a crash due to a too long request URL by moving some logic to a custom Strapi controller (see the new `keep-if-children-match` query parameter)

Apply feedback to the tables

---

frontend/src/components/charts/conservation-chart/index.tsx
frontend/src/components/charts/conservation-chart/legend/index.tsx
frontend/translations/en.json

This PR updates the visuals of the Conservation Coverage widget in order to avoid text overlap.
[SKY30-489](https://vizzuality.atlassian.net/browse/SKY30-489)
[SKY30-489]: https://vizzuality.atlassian.net/browse/SKY30-489?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update visuals of the Conservation Coverage widget

---

frontend/package.json
frontend/src/containers/map/sidebar/index.tsx
frontend/src/containers/map/sidebar/layers-panel/index.tsx
frontend/src/containers/map/store.ts
frontend/src/pages/_app.tsx
frontend/translations/en.json
frontend/yarn.lock

This PR does 3 things:
- make the map layer collapsed on initial load
- change the title of the map layers panel and expansion button from `Layers` to `Map Layers`
- Removes accidental duplication of google tag manger code
[_Link to the related task manager tickets_](https://skytruth.atlassian.net/browse/TECH-2491)
---

TECH-2491: Collapse map layers by default

---

frontend/package.json
frontend/src/pages/_app.tsx

This PR removes an unused import from a library that has been removed from the package.json. I'm not sure how this got past the pre-commit linter

Remove bad import

---

frontend/package.json
frontend/src/containers/map/sidebar/index.tsx

This code fixes a weird text overflow that happened with the Spanish version of the map layer toggle
Current:
This Change

Style fix for map layer toggle button

---

cms/Documentation.md
cms/config/sync/admin-role.strapi-super-admin.json
cms/config/sync/core-store.plugin_content_manager_configuration_content_types##api##location.location.json
cms/src/api/location/content-types/location/schema.json
cms/src/api/pa/content-types/pa/schema.json
cms/types/generated/contentTypes.d.ts
frontend/src/types/generated/strapi.schemas.ts

This PR does 2 main things
1. Updates the location to PAs relationship in strapi so that a location has many PA's instead of PA belongs to a location. This allows users to get Data Source information via a query to something like protected area stats: `protected area stats -> location -> PA -> data source` This support users being able to cite the data they get form us.
2. Adds API documentation
https://skytruth.atlassian.net/browse/TECH-2791
---

TECH-2791: Support for external API use

---

cms/package.json
cms/src/api/protection-coverage-stat/controllers/protection-coverage-stat.ts
cms/src/utils/Logger.ts

This PR is a hot fix for a bug when calling the get protection coverage stats endpoint. It breaks when the sort query param is parsed as an object instead of a string.
---

Hotfix: Handle sort parameter as object

---

cms/package.json
cms/src/api/protection-coverage-stat/controllers/protection-coverage-stat.ts
cms/tsconfig.json

This PR further updates the handling of sort params for the protection coverage stats controller. Sort params can be passed a  string
```javascript
'location.mpaa_protection_level_stats.percentage:desc,environment.name:asc'
```
An object
```javascript
{
location: {
mpaa_protection_level_statspercentage: 'desc'
},
environment: {
name: 'asc'
}
{
```
or an Array with entries that could be either of the above
```javascript
[
'location.mpaa_protection_level_stats.percentage:desc',
{
environment: {
name: 'asc'
}
}
]
This updates the method to handle all three cases.
```
---

Update sorting to handle array sort params

---

frontend/package.json
frontend/src/containers/map/content/map/popup/generic/index.tsx
frontend/yarn.lock

This PR fixes a bug caused by trying to destructure asynchronously fetched  data before the promise is resolved

Fix Popup Bug

---

frontend/package.json
frontend/src/containers/map/sidebar/main-panel/panels/details/widgets/terrestrial-conservation/index.tsx

The historic terrestrial data was calculated using a method that produces inaccurately low results. As we begin updating the data with accurate protected area numbers the time series will show false levels of improvement related to a change in data aggregation. This will be added back in when accurate historical data becomes available.
Deployed in dev:
This Change:
Before:
[_Link to the related task manager tickets_](https://skytruth.atlassian.net/browse/TECH-2888)
---

TECH-2888: Remove terrestrial time series

---

cms/config/sync/admin-role.strapi-author.json
cms/config/sync/admin-role.strapi-editor.json
cms/config/sync/admin-role.strapi-super-admin.json
cms/config/sync/core-store.plugin_content_manager_configuration_content_types##api##fishing-protection-level-stat.fishing-protection-level-stat.json
cms/config/sync/core-store.plugin_content_manager_configuration_content_types##api##mpaa-protection-level-stat.mpaa-protection-level-stat.json
cms/config/sync/core-store.plugin_content_manager_configuration_content_types##api##protection-coverage-stat.protection-coverage-stat.json
cms/config/sync/user-role.authenticated.json
cms/src/api/fishing-protection-level-stat/content-types/fishing-protection-level-stat/schema.json
cms/src/api/fishing-protection-level-stat/controllers/fishing-protection-level-stat.ts
cms/src/api/mpaa-protection-level-stat/content-types/mpaa-protection-level-stat/schema.json
cms/src/api/mpaa-protection-level-stat/controllers/mpaa-protection-level-stat.ts
cms/src/api/protection-coverage-stat/content-types/protection-coverage-stat/schema.json
cms/src/api/protection-coverage-stat/controllers/protection-coverage-stat.ts
cms/types/generated/contentTypes.d.ts
frontend/package.json
frontend/src/containers/map/sidebar/main-panel/panels/details/widgets/fishing-protection/index.tsx
frontend/src/containers/map/sidebar/main-panel/panels/details/widgets/marine-conservation/index.tsx
frontend/src/containers/map/sidebar/main-panel/panels/details/widgets/protection-types/index.tsx
frontend/src/containers/map/sidebar/main-panel/panels/details/widgets/terrestrial-conservation/index.tsx
frontend/src/types/generated/strapi.schemas.ts

Some of our data sources use different versions of GADM and EEZ data and, therefore, have different values for the total land and marine area of a country. This PR adds a `total_area` column to all of the statics tables (except habitat stats because that already existed as a calculated value). Additionally it adds some logic to allow our API upserting methods to pass the new field through and adds support to the front end to preferentially favor source specific total area (as opposed to what our database says the location area is).
Note: These columns will remain empty until we update and run our data pipelines with updates to pass this value through. For this reason the front end maintains fallback logic to use the current internal value of location total area. …

TECH-3067: Enable source specific total_area

---

cloud_functions/data_processing/main.py
cloud_functions/data_processing/pyproject.toml
cloud_functions/data_processing/src/params.py
cloud_functions/data_processing/src/utils/gcp.py
cloud_functions/data_processing/tests/fixtures/utils/util_mocks.py
cloud_functions/data_processing/tests/test_main.py
cloud_functions/data_processing/tests/utils/test_gcp.py
cms/config/sync/admin-role.strapi-author.json
cms/config/sync/admin-role.strapi-editor.json
cms/config/sync/user-role.authenticated.json
cms/config/sync/user-role.public.json
cms/src/api/location/documentation/1.0.0/location.json
cms/src/api/location/routes/location.ts
frontend/src/types/generated/location.ts

This PR primarily adds a code path to download GADM data to GCS. Additionally it adds some extra unit tests for existing functions, adds a post endpoint for locations data in the DB, updates some authenticated permissions 
This PR is in partial completion, but does not close, https://skytruth.atlassian.net/browse/TECH-3068
---

[TECH-3068]: Download GADM pipeline option

---

cms/config/sync/user-role.authenticated.json
frontend/package.json
frontend/src/containers/map/content/map/layer-manager/index.tsx
frontend/src/containers/map/content/map/sync-settings.ts
frontend/src/containers/map/sidebar/layers-panel/layers-group/index.tsx

Cleans up unused query params to try to reduce query param bloat, it also persists the run-as-of param if it's present.
More could be done here, there are layer specific query params for opacity and visibility but shorting those to `v` and `o` would require updating a bunch of config json blobs in the layer stable in the DB (downside of the cms). So I'm choosing to leave that as extra credit if we find out that we need more clean up in the url.
[TECH-3062](https://skytruth.atlassian.net/browse/TECH-3062)

TECH-3062: Clean up query params
